package oovies.model;

import java.util.Objects;

public class Actor{

    protected int actorId;
	protected String name;
	protected Gender gender;

    public enum Gender{M, F}

    // This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
    public Actor(int actorId, String name, Gender gender){
        this.actorId = actorId;
        this.name = name;
        this.gender = gender;
    }

    // This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.

    public Actor(int actorId){
        this.actorId = actorId;
    }

    // This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.
    public Actor(String name, Gender gender){
        this.name = name;
        this.gender = gender;
    }

    public int getActorId() {
        return this.actorId;
    }

    public void setActorId(int actorId) {
        this.actorId = actorId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Gender getGender() {
        return this.gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Actor)) {
            return false;
        }
        Actor actor = (Actor) o;
        return actorId == actor.actorId && Objects.equals(name, actor.name) && Objects.equals(gender, actor.gender);
    }

    @Override
    public int hashCode() {
        return Objects.hash(actorId, name, gender);
    }

    @Override
    public String toString() {
        return "{" +
            " actorId='" + getActorId() + "'" +
            ", name='" + getName() + "'" +
            ", gender='" + getGender() + "'" +
            "}";
    }

}